
language: ruby

cache:
    directories:
        - $HOME/.rvm/

install:
    - bundle

script:
    - rake

deploy:
    provider: rubygems
    api_key: "$RUBYGEMS_API_KEY"
    gem: homebrew_automation
    gemspec: homebrew_automation.gemspec
    on:
        tags: true
