
language: ruby

matrix:
    include:
        - os: osx
          osx_image: xcode6.4
          env: OSX_VERSION_NAME=yosemite
        - os: osx
          osx_image: xcode8
          env: OSX_VERSION_NAME=el_capitan
        - os: osx
          osx_image: xcode9.2
          env: OSX_VERSION_NAME=sierra

cache:
    directories:
        - $HOME/.rbenv/

before_install:
    - brew bundle
    - eval "$(rbenv init -)"
    - rbenv local
    - which ruby
    - which gem
    - gem install bundler rake
    - which bundle
    - which rake

install:
    - bundle

script:
    - rake
