
language: ruby
dist: trusty
sudo: false

cache:
    directories:
        - $HOME/.rbenv/

before_install:
    - which ruby
    - git clone https://github.com/rbenv/rbenv.git ~/.rbenv
    - eval "$(rbenv init -)"
    - rbenv local
    - which ruby
    - which gem
    - gem install bundler rake
    - which bundle
    - which rake

install:
    - bundle

script:
    - rake
